version: '3'

services:
  app:
    image: 'guardless/employee_test'
    ports:
    - "8182:8181"
    container_name: springdocker
    depends_on:
      - db_test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_test:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db_test:
    image: 'postgres:13.1-alpine'
    container_name: db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
volumes:
    database-data: # named volumes can be managed easier using docker-compose